packages:
  - name: instatus
    functions:
      - name: discord
        runtime: go:1.20
        environment:
          DISCORD_WEBHOOK_ID: "${DISCORD_WEBHOOK_ID}"
          DISCORD_WEBHOOK_TOKEN: "${DISCORD_WEBHOOK_TOKEN}"
